### PR TITLE
Update podspec to use Swift 4.1

### PR DESCRIPTION
**Pull request by onmyway133**
- Also, to test CircleCI 2.0 https://discuss.circleci.com/t/xcode-9-3-beta-4-release-for-circleci-2-0/20757/2

### CODE REVIEW

**Review by vadymmarkov — APPROVED** [review]

**Comment by anderscarling** [comment]
Not sure you actually need to explicitly set `SWIFT_VERSION` to 4.1.

When I use xcode build settings to set `Swift Language Version` to `Swift 4.1` it will just set `SWIFT_VERSION` to 4.0 in the .xcodeproj.

Might be me misunderstanding something though, if so I would love to be enlightened! :)

**Comment by onmyway133** [comment]
@anderscarling Hi, I don't know if it is still required now, but it was a problem last time for us.

**Comment by anderscarling** [comment]
@onmyway133 Are you looking to release these changes anytime soon? :)

**Comment by onmyway133** [comment]
@anderscarling Hi, I just released it to CocoaPods, can you check https://github.com/hyperoslo/Cheers/releases/tag/2.1.0 ?

**Pull request merged**
